modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
issueTrackerURL = "https://github.com/ItzApipAjalah/Sawit-Mod/issues"
displayURL = "https://github.com/ItzApipAjalah/Sawit-Mod"
license = "Insert License Here"

[[mods]]
modId = "sawitmod"
version = "${version}"
displayName = "sawitmod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""
logoFile = "icon.png"

[[dependencies.sawitmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sawitmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sawitmod]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
