# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = com.sawit.kotaklegend
archives_name = sawitmod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.20.5

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.97.8+1.20.5
neoforge_version = 20.5.21-beta

architectury_api_version=12.0.29

# Force Gradle to not use bad toolchains
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=/usr/lib/jvm/java-1.21.0-openjdk-amd64
org.gradle.java.home=/usr/lib/jvm/java-1.21.0-openjdk-amd64
