# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = com.sawit.kotaklegend
archives_name = sawitmod
enabled_platforms = fabric,forge,neoforge,quilt

# Minecraft properties
minecraft_version = 1.20.4

# Dependencies
architectury_api_version = 11.1.17
fabric_loader_version = 0.19.3
fabric_api_version = 0.97.3+1.20.4
forge_version = 1.20.4-49.2.2
neoforge_version = 20.4.251
quilt_loader_version = 0.30.1-beta.2
quilted_fabric_api_version = 9.0.0-alpha.8+0.97.0-1.20.4

# Force Gradle to not use bad toolchains
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=/usr/lib/jvm/java-1.21.0-openjdk-amd64
org.gradle.java.home=/usr/lib/jvm/java-1.21.0-openjdk-amd64
