modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
issueTrackerURL = "https://github.com/ItzApipAjalah/Sawit-Mod/issues"
displayURL = "https://github.com/ItzApipAjalah/Sawit-Mod"
license = "MIT"

[[mods]]
modId = "sawitmod"
version = "${version}"
displayName = "sawitmod"
authors = "burung25"
description = '''
MARI KITA MENYAWIT!!!!!!!!
'''
#logoFile = ""
logoFile = "icon.png"

[[dependencies.sawitmod]]
modId = "neoforge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.sawitmod]]
modId = "minecraft"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.sawitmod]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
